export const SUCCESS_REGISTER = 'SUCCESS_REGISTER'
export const ERROR_REGISTER = 'ERROR_REGISTER'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const ERROR_LOGIN = 'ERROR_LOGIN'
export const USER_DATA = 'USER_DATA'
export const ERROR_USER_DATA = 'ERROR_USER_DATA'
export const LOGOUT = 'LOGOUT'
//GETTING ANY USER DATA
export const ANY_USER_DATA = "ANY_USER_DATA"
export const ANY_ERROR_USER_DATA = "ANY_ERROR_USER_DATA"

//Classrooms Flags
export const ADD_CLASSROOM = "ADD_CLASSROOM"
export const ADD_CLASSROOM_ERROR = "ADD_CLASSROOM_ERROR"
export const DELETE_CLASSROOM = "DELETE_CLASSROOM"
export const TOGGLE_PUBLIC = "TOGGLE_PUBLIC"
export const EDIT_CLASSROOM = "EDIT_CLASSROOM"
export const SAVE_EDIT_DATA = "SAVE_EDIT_DATA"
export const CANCEL = "CANCEL"

export const GET_CLASSROOM = "GET_CLASSROOM"
export const GET_CLASSROOM_ERROR = "GET_CLASSROOM_ERROR"
export const DELETE_ERROR = "DELETE_ERROR"
export const EDIT_ERROR = "EDIT_ERROR"

//THIS FLAG IS FOR GETTING RESPONSE AFTER SEND REQUEST
export const SEND_REQ_RESPONSE = "SEND_REQ_RESPONSE"
export const SEND_REQ_RESPONSE_ERROR = "SEND_REQ_RESPONSE_ERROR"
export const CLEAR_REQ_STATE = "CLEAR_REQ_STATE"

//MEMBERS 
export const REMOVE_MEMBER_SUCCESS = "REMOVE_MEMBER_SUCCESS"
export const REMOVE_MEMBER_ERROR = "REMOVE_MEMBER_ERROR"
export const CLEAR_REMOVE_STATE = 'CLEAR_REMOVE_STATE'

//POSTS
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS"
export const ADD_POST_ERROR = "ADD_POST_ERROR"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_ERROR = "GET_POST_ERROR"
export const CLEAR_ERROR_SAVE = "CLEAR_ERROR_SAVE"

export const GET_JOINED_CLASSROOM = 'GET_JOINED_CLASSROOM'
export const GET_JOINED_CLASSROOM_ERROR = 'GET_JOINED_CLASSROOM_ERROR'